#HDMI
#Clock
set_property PACKAGE_PIN P28 [get_ports vid_clk]
set_property IOSTANDARD LVCMOS25 [get_ports vid_clk]
#Data
set_property PACKAGE_PIN U24 [get_ports vid_data[0]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[0]]
set_property PACKAGE_PIN T22 [get_ports vid_data[1]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[1]]
set_property PACKAGE_PIN R23 [get_ports vid_data[2]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[2]]
set_property PACKAGE_PIN AA25 [get_ports vid_data[3]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[3]]
set_property PACKAGE_PIN AE28 [get_ports vid_data[4]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[4]]
set_property PACKAGE_PIN T23 [get_ports vid_data[5]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[5]]
set_property PACKAGE_PIN AB25 [get_ports vid_data[6]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[6]]
set_property PACKAGE_PIN T27 [get_ports vid_data[7]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[7]]
set_property PACKAGE_PIN AD26 [get_ports vid_data[8]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[8]]
set_property PACKAGE_PIN AB26 [get_ports vid_data[9]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[9]]
set_property PACKAGE_PIN AA28 [get_ports vid_data[10]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[10]]
set_property PACKAGE_PIN AC26 [get_ports vid_data[11]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[11]]
set_property PACKAGE_PIN AE30 [get_ports vid_data[12]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[12]]
set_property PACKAGE_PIN Y25 [get_ports vid_data[13]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[13]]
set_property PACKAGE_PIN AA29 [get_ports vid_data[14]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[14]]
set_property PACKAGE_PIN AD30 [get_ports vid_data[15]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[15]]
set_property PACKAGE_PIN Y28 [get_ports vid_data[16]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[16]]
set_property PACKAGE_PIN AF28 [get_ports vid_data[17]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[17]]
set_property PACKAGE_PIN V22 [get_ports vid_data[18]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[18]]
set_property PACKAGE_PIN AA27 [get_ports vid_data[19]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[19]]
set_property PACKAGE_PIN U22 [get_ports vid_data[20]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[20]]
set_property PACKAGE_PIN N28 [get_ports vid_data[21]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[21]]
set_property PACKAGE_PIN V21 [get_ports vid_data[22]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[22]]
set_property PACKAGE_PIN AC22 [get_ports vid_data[23]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data[23]]
#video active
set_property PACKAGE_PIN V24 [get_ports vid_active_video]
set_property IOSTANDARD LVCMOS25 [get_ports vid_active_video]
#Sync signals
set_property PACKAGE_PIN R22 [get_ports vid_hsync]
set_property IOSTANDARD LVCMOS25 [get_ports vid_hsync]
set_property PACKAGE_PIN U21 [get_ports vid_vsync]
set_property IOSTANDARD LVCMOS25 [get_ports vid_vsync]

#Locked signal -> LED
set_property PACKAGE_PIN Y21  [get_ports vid_locked]
set_property IOSTANDARD LVCMOS25 [get_ports vid_locked] 